version: '3.8'

services:
  bap-app-mca:
    build: .
    image: bap-onest-lite-mca
    container_name: bap-onest-lite-mca
    depends_on:
      redis-mca:
        condition: service_healthy
      db-mca:
        condition: service_healthy
    volumes:
      - ./config:/app/config
      - ./app/logs:/app/app/logs
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    command: ["./bap-onest-lite", "${CONFIG_FILE}"]

  redis-mca:
    image: redis:7.2
    container_name: bap-redis-mca
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db-mca:
    image: postgres:16
    container_name: bap-postgres-mca
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - mca-onest-bap-lite_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mca-onest-bap-lite_postgres_data:
    external: true
